# -*- coding: utf-8 -*-
"""Project-Phase 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PnN4Pwo-QkaoN6n8gqemMK6OQVObZOI5

Upload the dataset
"""

from google.colab import files

uploaded = files.upload()

"""Load the Dataset"""

import pandas as pd
# Read the dataset
# is it visible?
df = pd.read_csv("/content/road_accident_dataset.csv")
df.head()

"""Data Exploration"""

# Display first few rows
df.head()

"""Data Exploration"""

# Shape of the dataset
print("Shape:", df.shape)
# Column names
print("Columns:", df.columns.tolist())
# Data types and non-null values
df.info()
# Summary statistics for numeric features
df.describe()

"""Check for Missing Values and Duplicates"""

# Check for missing values
print(df.isnull().sum())
# Check for duplicates
print("Duplicate rows:", df.duplicated().sum())

"""Visualize a Few Features"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set(style="whitegrid")

# Visualize distribution of accident severity
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='Accident Severity', palette='Set2')
plt.title('Distribution of Accident Severity')
plt.xlabel('Accident Severity')
plt.ylabel('Count')
plt.show()

# Visualize accidents by day of the week
plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='Day of Week', order=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], palette='Set1')
plt.title('Accidents by Day of the Week')
plt.xlabel('Day of Week')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""6: Identify Target and Features"""

target_column = 'Accident Severity'
columns_to_drop = ['Search by all fields']  # Optional: Add more if needed
# Drop irrelevant columns
df = df.drop(columns=columns_to_drop, errors='ignore')

# Define target and features
target = 'Accident Severity'
features = df.columns[df.columns != target]

X = df[features]
y = df[target]

print("Features selected for prediction:")
print(features.tolist())
print("\nTarget variable:", target)

"""7: Convert Categorical Columns to Numerical"""

from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()

# Apply Label Encoding to ordinal or binary columns (you can skip those intended for One-Hot Encoding in the next step)
label_encoder = LabelEncoder()

# Encode columns with 2 or few values (like 'Driver Gender', 'Urban/Rural', etc.)
for col in categorical_cols:
    if X[col].nunique() <= 2:  # Binary columns
        X[col] = label_encoder.fit_transform(X[col])
        print(f"Label encoded: {col}")
    else:
        print(f"Skipped for one-hot encoding later: {col}")

"""8: One-Hot Encoding"""

# Re-identify categorical columns (in case some were label encoded already)
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()

# Apply One-Hot Encoding using pandas
X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

print("Original shape:", X.shape)
print("New shape after one-hot encoding:", X_encoded.shape)
print("\nExample of new encoded columns:")
print(X_encoded.columns[:10].tolist())  # Displaying first 10 columns

"""9: Feature Scaling"""

from sklearn.preprocessing import StandardScaler

# Initialize scaler
scaler = StandardScaler()

# Fit and transform the features
X_scaled = scaler.fit_transform(X_encoded)

# Convert scaled features back to a DataFrame for readability (optional)
X_scaled_df = pd.DataFrame(X_scaled, columns=X_encoded.columns)

print("Feature scaling completed.")
print("Mean of first 5 features (approx):\n", X_scaled_df.iloc[:, :5].mean())
print("\nStandard deviation of first 5 features (approx):\n", X_scaled_df.iloc[:, :5].std())

"""10: Train-Test Split"""

from sklearn.model_selection import train_test_split

# Split into train and test sets (80/20 split)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled_df, y, test_size=0.2, random_state=42, stratify=y)

print("Train-Test split completed.")
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train distribution:\n", y_train.value_counts(normalize=True))
print("y_test distribution:\n", y_test.value_counts(normalize=True))

"""11: Model Building"""

from sklearn.ensemble import RandomForestClassifier

# Initialize the model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

print("Model training completed.")

"""12: Evaluation"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Predict on test data
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=model.classes_, yticklabels=model.classes_)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""13: Make Predictions from New Input"""

# Convert to DataFrame
new_input_df = pd.DataFrame([new_input])

# Fix: use pd.concat instead of deprecated append
for col in ['Driver Gender', 'Urban/Rural']:
    combined = pd.concat([df[col], new_input_df[col]], ignore_index=True)
    label_encoder.fit(combined)
    new_input_df[col] = label_encoder.transform(new_input_df[col])

# One-hot encode remaining categorical columns
new_input_encoded = pd.get_dummies(new_input_df)

# Align new input columns to training feature columns
new_input_encoded = new_input_encoded.reindex(columns=X_encoded.columns, fill_value=0)

# Scale features using the previously fitted scaler
new_input_scaled = scaler.transform(new_input_encoded)

# Predict the accident severity
prediction = model.predict(new_input_scaled)
print("Predicted Accident Severity:", prediction[0])

"""14: Convert to DataFrame and Encode"""

def preprocess_new_input(input_dict, original_df, label_enc_cols, scaler, X_encoded_columns):
    # Convert input dictionary to DataFrame
    input_df = pd.DataFrame([input_dict])

    # Label encode specified binary categorical columns
    le = LabelEncoder()
    for col in label_enc_cols:
        combined = pd.concat([original_df[col], input_df[col]], ignore_index=True)
        le.fit(combined)
        input_df[col] = le.transform(input_df[col])

    # One-hot encode other categorical columns
    input_encoded = pd.get_dummies(input_df)

    # Align input with model training columns, fill missing columns with 0
    input_encoded = input_encoded.reindex(columns=X_encoded_columns, fill_value=0)

    # Scale features
    input_scaled = scaler.transform(input_encoded)

    return input_scaled

"""Step 15: Predict the Final Grade"""

# Predict with the model using preprocessed input (from Step 14)
predicted_class = model.predict(new_input_scaled)[0]

# If target labels are strings, prediction is already readable
# If target was encoded numerically, you can inverse-transform like this:

# Example: if you used LabelEncoder for target
# target_le = LabelEncoder()
# target_le.fit(df['Accident Severity'])  # Fit on original target column

# predicted_label = target_le.inverse_transform([predicted_class])[0]
# print("Predicted Accident Severity:", predicted_label)

print("Predicted Accident Severity:", predicted_class)

"""16: Deployment - Building an Interactive App"""

!pip install gradio
import gradio as gr

# Define input components matching your features
def predict_accident_severity(
    Year, Month, Day_of_Week, Time_of_Day, Urban_Rural, Road_Type, Weather_Conditions, Visibility_Level,
    Number_of_Vehicles_Involved, Speed_Limit, Driver_Age_Group, Driver_Gender, Driver_Alcohol_Level,
    Driver_Fatigue, Vehicle_Condition, Pedestrians_Involved, Cyclists_Involved, Number_of_Injuries,
    Number_of_Fatalities, Emergency_Response_Time, Traffic_Volume, Road_Condition, Accident_Cause,
    Insurance_Claims, Medical_Cost, Economic_Loss, Region, Population_Density
):
    # Create input dictionary
    input_data = {
        'Year': Year,
        'Month': Month,
        'Day of Week': Day_of_Week,
        'Time of Day': Time_of_Day,
        'Urban/Rural': Urban_Rural,
        'Road Type': Road_Type,
        'Weather Conditions': Weather_Conditions,
        'Visibility Level': Visibility_Level,
        'Number of Vehicles Involved': Number_of_Vehicles_Involved,
        'Speed Limit': Speed_Limit,
        'Driver Age Group': Driver_Age_Group,
        'Driver Gender': Driver_Gender,
        'Driver Alcohol Level': Driver_Alcohol_Level,
        'Driver Fatigue': Driver_Fatigue,
        'Vehicle Condition': Vehicle_Condition,
        'Pedestrians Involved': Pedestrians_Involved,
        'Cyclists Involved': Cyclists_Involved,
        'Number of Injuries': Number_of_Injuries,
        'Number of Fatalities': Number_of_Fatalities,
        'Emergency Response Time': Emergency_Response_Time,
        'Traffic Volume': Traffic_Volume,
        'Road Condition': Road_Condition,
        'Accident Cause': Accident_Cause,
        'Insurance Claims': Insurance_Claims,
        'Medical Cost': Medical_Cost,
        'Economic Loss': Economic_Loss,
        'Region': Region,
        'Population Density': Population_Density
    }

    # Preprocess and predict using Step 14 function
    input_scaled = preprocess_new_input(input_data, df, ['Driver Gender', 'Urban/Rural'], scaler, X_encoded.columns)
    prediction = model.predict(input_scaled)[0]
    return prediction

# Define Gradio input components (you can adjust types and defaults)
iface = gr.Interface(
    fn=predict_accident_severity,
    inputs=[
        gr.Number(label="Year", value=2024),
        gr.Number(label="Month", value=5),
        gr.Dropdown(label="Day of Week", choices=df['Day of Week'].unique().tolist()),
        gr.Number(label="Time of Day", value=12),
        gr.Dropdown(label="Urban/Rural", choices=df['Urban/Rural'].unique().tolist()),
        gr.Dropdown(label="Road Type", choices=df['Road Type'].unique().tolist()),
        gr.Dropdown(label="Weather Conditions", choices=df['Weather Conditions'].unique().tolist()),
        gr.Dropdown(label="Visibility Level", choices=df['Visibility Level'].unique().tolist()),
        gr.Number(label="Number of Vehicles Involved", value=2),
        gr.Number(label="Speed Limit", value=60),
        gr.Dropdown(label="Driver Age Group", choices=df['Driver Age Group'].unique().tolist()),
        gr.Dropdown(label="Driver Gender", choices=df['Driver Gender'].unique().tolist()),
        gr.Dropdown(label="Driver Alcohol Level", choices=df['Driver Alcohol Level'].unique().tolist()),
        gr.Dropdown(label="Driver Fatigue", choices=df['Driver Fatigue'].unique().tolist()),
        gr.Dropdown(label="Vehicle Condition", choices=df['Vehicle Condition'].unique().tolist()),
        gr.Number(label="Pedestrians Involved", value=0),
        gr.Number(label="Cyclists Involved", value=0),
        gr.Number(label="Number of Injuries", value=0),
        gr.Number(label="Number of Fatalities", value=0),
        gr.Number(label="Emergency Response Time", value=10),
        gr.Number(label="Traffic Volume", value=100),
        gr.Dropdown(label="Road Condition", choices=df['Road Condition'].unique().tolist()),
        gr.Dropdown(label="Accident Cause", choices=df['Accident Cause'].unique().tolist()),
        gr.Dropdown(label="Insurance Claims", choices=df['Insurance Claims'].unique().tolist()),
        gr.Number(label="Medical Cost", value=0),
        gr.Number(label="Economic Loss", value=0),
        gr.Dropdown(label="Region", choices=df['Region'].unique().tolist()),
        gr.Dropdown(label="Population Density", choices=df['Population Density'].unique().tolist()),
    ],
    outputs=gr.Textbox(label="Predicted Accident Severity"),
    title="Road Accident Severity Predictor",
    description="Input accident parameters to predict severity."
)

iface.launch()

"""17: Create a Prediction Function"""

def predict_accident_severity_from_input(input_dict):
    """
    Takes a dictionary of raw input features,
    applies preprocessing (encoding, scaling),
    and returns the predicted accident severity.
    """
    # Preprocess input
    binary_cols = ['Driver Gender', 'Urban/Rural']
    input_scaled = preprocess_new_input(
        input_dict=input_dict,
        original_df=df,
        label_enc_cols=binary_cols,
        scaler=scaler,
        X_encoded_columns=X_encoded.columns
    )

    # Predict
    prediction = model.predict(input_scaled)[0]

    return prediction

"""18: Create the Gradio Interface"""

!pip install gradio
import gradio as gr
import numpy as np
from sklearn.linear_model import LinearRegression

# Dummy model for testing
model = LinearRegression()
X = np.random.rand(50, 5)
y = np.random.randint(0, 21, 50)
model.fit(X, y)

# Prediction function
def predict_grade(school, gender, age, study_time, g1, g2):
    numeric = [
        1 if school == 'GP' else 2,
        1 if gender == 'M' else 2,
        float(study_time),
        float(g1)
    ]
    return f"🎯 Predicted Final Grade (G3): {round(model.predict([numeric])[0], 2)}"

# Interface
gr.Interface(
    fn=predict_grade,
    inputs=[
        gr.Dropdown(['GP', 'MS'], label="School"),
        gr.Dropdown(['M', 'F'], label="Gender"),

        gr.Number(label="Weekly Study Time (1-4)"),
        gr.Number(label="G1 (1st Period Grade)")
    ],
    outputs="text",
    title="🎓 Student Grade Predictor",
    description="Fill in basic info to predict the final grade (G3)."
).launch(share=True)